### ISSUE TITLE
Update information for fflate

### ISSUE THREAD

**Issue by 101arrowz** [greggman/unzipit#18]
Hello there! I'm the author of fflate and came across your library; it seems to solve many of the same problems as my own. I wanted to suggest two things:
- fflate now supports streaming ZIP files in and out, so the information on the website is inaccurate. Admittedly it works by reading local file headers, but the system functions for the vast majority of files, so I ask you update to another advantage. Perhaps the fact that your solution (brilliant, by the way - I never even thought of Range headers to read the EOCD) is more resilient than mine.
- I see you use UZIP's `inflateRaw` to make your code function. Since you promote streaming data, you may want to consider using fflate's own `Inflate` stream class so you can also stream the responses from your fetch calls.

Last thing - as part of fflate, I developed a solution for creating Worker threads from synchronous code. It reduces bundle size, removes a network request, and works on any platform without having to specify a worker URL. If you'd like to implement that, let me know. You can already take a look at [this package](https://github.com/101arrowz/isoworker) for some inspiration.

Overall, it's awesome that we have multiple modern projects to replace the archaic ones (JSZip and Pako). I'm glad you've spent the time to maintain this and hope you find this information useful :)

**Comment by greggman** [comment]
fflate sounds great. Looking at your API though I don't see how you stream zip files. I mean I get that you can take a stream in but the result is the entire file unzipped. Maybe I'm mis-understanding what you mean.

I did notice you had zero config workers. I didn't look at your solution yet, I only imagined it uses the fact that you can get the source for functions so you could generate the code needed for the worker? But yes, I did think about looking into how you actually did that.

**Comment by 101arrowz** [comment]
The library was just updated today; you'll see that there is now an `Unzip` class that takes a stream as an input and calls a handler whenever it discovers a new file. The handler receives a stream object. When `start()` is called on said stream object, the stream begins to decompress the data that was already found and any future data that is found as the entire ZIP stream continues. Basically, you can do as little or as much processing as you like.

The zero config workers do exactly that; they generate the source code from the function. The more impressive part is that it works after minification. That took a lot of effort because you have literally no ability to control what the minifier names things. I'm looking to share my solution more publicly later, but I saw you were doing something similar so I thought I would suggest it.

**Comment by greggman** [comment]
Ok, so IIUC fflate can now let the user read one file at time, in order, all files have to read (by fflate)?

```
/ Unzip object
const unzipper = new fflate.Unzip();

// This function will almost always have to be called. It is used to support
// compression algorithms such as BZIP2 or LZMA in ZIP files if just DEFLATE
// is not enough (though it almost always is).
// If your ZIP files are not compressed, this line is not needed.
unzipper.register(fflate.UnzipInflate);

const neededFiles = ['file1.txt', 'example.json'];

// Can specify handler in constructor too
unzipper.onfile = (err, filename, file) => {
  if (err) {
    // The filename will usually exist here too
    console.log(`Error with file ${filename}: ${err}`);
    return;
  }
  // filename is a string, file is a stream
  if (neededFiles.includes(filename)) {
    file.ondata = (err, dat, final) => {
      // Stream output here
      console.log(dat, final);
    };
    
    // You should only start the stream if you plan to use it to improve
    // performance. Only after starting the stream will ondata be called.
    file.start();
  }
};

unzipper.push(zipChunk1);
unzipper.push(zipChunk2);
unzipper.push(zipChunk3, true);
```

unzipit if you have a zip file that contains (a,b,c,d,e,f) you can just read e if that's all you want. Only e will be downloaded if you use range requests on the browser or files on node, only e will be decompressed, only e will take memory. further the API seem simpler. Taking your example above with unzipit it's this

```
const {entries} = await unzipit.unzip(new HTTPRangeReader(url));
const file1 = await entries['file1.txt'].text();
const file2 = await entries['example.json'].json();
```

or this

```
const {entries} = await unzipit.unzip(new HTTPRangeReader(url));
const files = await Promise.all(['file1.txt', 'example.json'].map(name => entries[name].text());
```

Super simple. Don't get callbacks for files I don't care about.

I'd be happy to use fflate and deprecate this library if the API was more simple like unzipit and I could load only parts of the files I care about and further, that I never see the memory (can go straight to blobs). Those two use cases are why I ended up writing this. The API being simple is because async/await, no callbacks. (Well since it's based on promises you're free to use `then` if you want callbacks

```
unzipit.unzip(url).then(({entries}) =>  { .... })
```

I also had no use for sync reading. async/await lets me write sync looking code and since the user will be supplying zip files I can't really freeze the browser waiting for results. I only bring that up because no sync probably made it easier to write?

My use case, I have a .cbz file (a .zip file of images). I have thumbnails external to that file. Some file has 100 images. User clicks image 77. I need to go straight to image 77, get a blob, and URL for that blob, display an img (ie, `<img src="blob-url">`) as quick as possible. So I needed to be able to jump straight to image 77 without having to read/download/or decompress images 1 to 76.

I don't have a lot of desire to maintain this library, I just wrote it out of necessity so if someone else makes something that solves the same issues and is well designed I'll be happy to use it.

**Comment by 101arrowz** [comment]
I see know that these libraries were made for different purposes. I'm not asking you to deprecate this library or promote mine or do anything drastic; I love open source and definitely don't want to force others to use my stuff just because it's mine. I wanted to help improve this implementation but if you have a specific use case for it and aren't trying to make it a general-purpose library, I understand completely.

The idea with `fflate` is to support everyone at the expense of brevity. There's a reason I didn't use `Promise` or `SharedArrayBuffer` or use longer names for private fields on classes or use an existing compression implementation - I wanted to make the fastest and smallest library that supports old browsers like IE11 while doing anything you could possibly want. Not being locked into `Range` requests for streaming to work is a huge plus for legacy codebases or people who need to decompress a user-uploaded file on client-side.

At the same time, `unzipit` targets a specific use case with a much nicer API. The fact that you don't need to deal with callbacks or even write the code to fetch the ZIP file yourself is insanely useful for anyone with your use case. You don't support IE11 and that's not a big deal for what you're doing. I would rather use this myself if I didn't care about older browsers.

Just for clarification, `fflate`'s streaming unzip doesn't decompress every file and only reads the local file headers. If you `.start()` the stream associated with an individual file, only then will it read and decompress that file. You don't need to specify callbacks for files you don't want, but you still will be given every file and will have to choose if you want each one or not. Blob conversion is quite literally a line: `new Blob([data.buffer])`, but of course that's not truly seamless. In short, though, `fflate` expects serial access to data and is as performant as possible while doing so, while `unzipit` expects random access to data and can be more performant for the use case you have as a result.

At the end of the day, I'm happy with whatever you think is best. I only made this issue because I was excited to see someone else also trying to improve the JS ecosystem in the same field as me. To be honest, this is my first majorly successful project, so it's all quite new to me. Seeing that this is a need-driven project and that you have a totally different set of parameters, I would assume that you're not interested in changing anything at the moment, but just let me know if you are. Hope that clears things up!

**Comment by greggman** [comment]
unzipit is does not require range requests. It's an option. 

As for IE support, not even microsoft supports IE but for those that want IE support they can transpile. No need to waste time supporting it directly. React for example is one of the most prolific libraries but its source is not IE compatible. You just run it through Babel and spit out IE compatible code if you need it.

As for small names. That's something a compressor handles. There's no need to write obfusticated hard to read and hard to understand code. Let the computer obfuscate it for you. It can even look at the frequency of usage of each name and choose shorter names for the names that appear more. Google's Closure compiler will even inline functions and do other crazy optimizations.

I think I'm confused about your streaming claim.  If I have a zip file that is has 6 files, a, b, c, d, e, f. The contents of the zip is ABCDEF(TOC).  I don't see how fflate can steam that file. You can't read a zip file front to back. You absolutely have to jump to the end of the file, read the TOC (table of contents) and use that to find the files.  Scanning local headers is against the zip spec. This is because as far as headers of files go a zip file can have multiple versions of the same file and or other non-zip related data in the file. Only the TOC points to the correct contents of the file.

So fflate has to download the entire file to get to the TOC which means it can not stream zip files. Either that or it's not a standard compliant implementation, looking at local headers is not correct by the zip spec. There are plenty of zip files out their that will fail when read that way.

As for blobs, the issue is not that it's one line. The issue is that the worker can create the blobs so the it happens off the main thread.

**Comment by 101arrowz** [comment]
It may not have been your intention, but your response feels quite aggressive. I wasn't intending any harm with this issue, and I'm sorry if I offended you.

When I say IE support of course I'm transpiling, but you still can't use `Promise` or `SharedArrayBuffer` or `fetch` without polyfilling too, and that's something I strived to avoid. I use ES6 syntax and conventions with the ES5 web spec.

No, the compressor does not shorten the length of names of fields on classes. Not by default anyway in Uglify or Terser, the two largest minifiers. Even if you enable it, the field name minification breaks the standard JS library (e.g. Math.random becomes Math.n). Using longer names is actually worse. The closure compiler is not good enough; I've tried it and it breaks my code half the time while still being larger than my hand-optimized code.

No, `fflate` is not standards compliant and doesn't aim to be. Problem is, if you try to be standards compliant you sacrifice performance. Did you know that UZIP, which AFAICT you use for decompression, isn't standards compliant either? If it were, it would need to call one extra function per byte read, but because it assumes the maximum length of a Huffman + LZ77 block is 131072 bytes, it doesn't need that function call for the vast majority of bytes read. There is no actual limit on the length of one of those blocks, so in theory, a compressor could create a totally valid file that breaks on this library, and the only way to avoid it is to use `pako`, which is actually standards compliant and much, much slower as a result. Same thing here, I look for the magic number by iterating through every byte that isn't part of a file. Most compressors don't leave room between files in practice, so really I search 1 byte on average. It's a 4-byte sequence that is invalid ASCII and very difficult to create in any file, really. You'd have to intentionally try to break the decompressor if you wanted the streaming unzipper to fail. And by the way, the creator of the Zlib library and the GZIP file format/library Mark Adler [has made a streaming unzip tool](https://github.com/madler/sunzip). Say what you want, it works.

If you want Blob creation to happen off the main thread, fair enough. I'm not asking you to switch over. I never was. The point of this issue was to ask you to update the information on your webpage and to let you know some ways in which you could improve your library, but it doesn't really matter to me if you don't change anything.

**Comment by greggman** [comment]
And I only intended to do the same. You could make your library standards compliant. Or you could at least mention it's not standards compilant since it won't read fully valid zip files. I'm not sure what your point was that someone else also wrote a buggy zip reader.  "Say what you want, it works" - no, it doesn't. It works for some subset, but it's not a valid zip reader anymore than a JSON parser that only reads ASCII would actually be a JSON parser yet still work for some subset of JSON data.

It is not hard to create a zip file that will break. It's by design. The entire point of the TOC being at the end of the file is so you can update files by just appending new version to the end of the file and then writing a new TOC. You've got a 100meg file and want to update one 5k text file, you read the old TOC, append the new text file, write a new TOC. Only 5k+TOC written instead of 100meg + 5k + TOC.  The original pkzip did this often. That's what the freshen feature did because re-writing a zip file across 70 floppy disks was not something anyone want to do.

**Comment by 101arrowz** [comment]
I'm not interested in having a debate about this. You've been combative throughout this discussion, but I didn't want a fight. Yes, `fflate` is not standards compliant; just as `unzipit` is not and `sunzip` is not and macOS Archive Utility is not. It's unlikely that anyone will ever find a non-contrived file that breaks fflate, just like it's unlikely that anyone will ever find an actual deflate block above 2<sup>17</sup> bytes that will break unzipit. Although in both cases, it's possible to create a file that will cause both implementations to explode. I'd rather leave this at a difference of goal for the two libraries rather than continuing a pointless discussion.

**Comment by greggman** [comment]
> You've been combative throughout this discussion

I have not been combative at all. I simply stated my opinion, not reading the TOC is not a zip library. Maybe you could call it a zip recovery library. In fact, pkzip included a pkzipfix.exe that would go through and extract files based on the local file info and skip the TOC.

As for sunzip BTW, it at least does try to fix things at the end when it actually gets to the TOC. It doesn't just ignore it. Of course It's likely at that point it's already written files it shouldn't have written or seen contents it shouldn't have seen.
